# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-01 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_manager', '0005_auto_20200301_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosttab',
            name='port',
            field=models.PositiveSmallIntegerField(default=22),
        ),
    ]
