# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-01 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_manager', '0006_auto_20200301_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='project_tab',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='project_tab',
            field=models.ManyToManyField(to='remote_manager.ProjectTab'),
        ),
    ]
